import type { Metadata } from "next";
import { geistSans, geistMono } from "@/lib/font";
import "./globals.css";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const fontClasses = `${geistSans.className} ${geistMono.className} antialiased`;

  return (
    <html lang="en">  
      <body className="antiliased text-gray-800" suppressHydrationWarning >
        <NavBar />
        <main className="container px-8 mx-auto xl:px-5 max-w-screen-lg py-5 lg:py-8">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
