import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    <body className="antialiased text-gray-800 flex min-h-screen flex-col">
      <div className="container px-8 mx-auto xl:px-5 max-w-screen-lg">
        <NavBar />
        <main className="py-5 lg:py-8">
          {children}
        </main>
        <Footer />
      </div>
    </body>
  </html>
  );
}
