import type { Metadata } from "next";
import { geistSans, geistMono } from "@/lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const fontClasses = `${geistSans.className} ${geistMono.className} antialiased`;

  return (
    <html lang="en">
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
